******************************************************************
 
Info  : Starting CT Translator 
Info  : HyperWorks Version 14.0.0.88 
Info  : Using CT Library Version 2015-SP3-01 
Info  : Reading file E:\Work\Test2\sbao-fcm-interstage2-mpi\sbao-fcm-interstage2-mpi\example\newDB\0045\sample.45\Hypermesh\Interstage_Hole.New.CATPart on 10-28-2019 08:52:56 
Info  : Using C:\Program Files\Altair\14.0\io\afc_translators\bin\win64\ct\ct_reader.dll 
Info  : Reading initialization file C:/Program Files/Altair/14.0/io/afc_translators/bin/win64/ct_reader.ini 
 
 @AttributesAsMetadata       = off 
 @AvoidThirdPartyConversion  = on 
 @ImportBlanked              = off 
 @DensityAsMetadata          = on 
 @ImportFreeCurves           = on 
 @ImportFreePoints           = on 
 @TagsAsMetadata             = on 
 @SkipCreationOfSolid        = off 
 @ColorsAsMetadata           = off 
 @FullNameAsMetadata         = off 
 @OriginalIdAsMetadata   = off 
 @SplitComponentsByBody      = off 
 @SplitComponentsByPart      = off 
 @ShrinkSurfaces      = off 
 @RemoveTinySegInCompositeCurves  = off 
 @DisableSurfaceRelimitation  = off 
 @StitchingAcrossBodies      = off 
 @ImportForVisualizationOnly = off 
 @ReadCompositeData = off 
 @ReadCompositeData = off 
 @ReadAssemblyStructureOnly = off 
 
Info  : CT License Key  = altair%0yyd0r6v0wa80f0y107y1b2z107y19l619l60n5011bt19l601i800zo0imx00zo0u410bum1dow1dr60u410ywi0ywi0ywi01i8 
Info  : CT License Key Initialization Completed Successfully 
Info  : Current prefix for created metadata =  
Reading  E:\Work\Test2\sbao-fcm-interstage2-mpi\sbao-fcm-interstage2-mpi\example\newDB\0045\sample.45\Hypermesh\Interstage_Hole.New.CATPart 

******************************************************************
 
