Info:     Reading NASTRAN from E:/Work/Test2/sbao-fcm-interstage2-mpi/sbao-fcm-interstage2-mpi/example/newDB/0045/sample.45/Nastran/Interstage.bdf using C:\Program Files\Altair\14.0\io\model_readers\feinput\bin\win64\nastran.exe on 10-28-2019 08:53:37.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Vectorcols.
Info:     Processing Vectors.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Sets.
Info:     Processing Load Steps.
Info:     Processing Designvars.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Dequations.
Info:     Processing Optiresponses.
Info:     Processing Dvprels.
Info:     Processing Opticonstraints.
Info:     Processing Objectives.
Info:     Processing Opticontrols.
Info:     Processing Optidscreens.
Info:     Processing Tags.
Info:     Processing Ddvals.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
